import sqlite3
import pandas as pd
import os

# Construct absolute path to DB
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DB_PATH = os.path.join(BASE_DIR, "hobart.db")

def calculate_kpis():
    conn = sqlite3.connect(DB_PATH)
    
    print("--- Calculating Pinball KPIs ---")
    
    # 1. Transfer Counts per Ticket (Using Window Functions to detect changes)
    # We only care when the desk CHANGES.
    # We filter out NULL desks.
    print("Querying transfer stats...")
    
    query_transfers = """
    WITH DeskChanges AS (
        SELECT 
            sr_id, 
            jur_assignedgroup_id,
            LAG(jur_assignedgroup_id) OVER (PARTITION BY sr_id ORDER BY creationdate) as prev_desk
        FROM activity
        WHERE jur_assignedgroup_id IS NOT NULL
    )
    SELECT 
        sr_id,
        COUNT(*) as total_actions,
        SUM(CASE WHEN jur_assignedgroup_id != prev_desk THEN 1 ELSE 0 END) as transfer_count,
        COUNT(DISTINCT jur_assignedgroup_id) as distinct_desks
    FROM DeskChanges
    GROUP BY sr_id
    HAVING transfer_count > 0;
    """
    
    df_transfers = pd.read_sql_query(query_transfers, conn)
    
    # 2. Desk "Ricochet" Stats (Outbound Transfers)
    # Count how many times a desk appears as 'prev_desk' in a transfer
    print("Querying desk performance...")
    query_desk_stats = """
    WITH DeskChanges AS (
        SELECT 
            jur_assignedgroup_id as current_desk,
            LAG(jur_assignedgroup_id) OVER (PARTITION BY sr_id ORDER BY creationdate) as prev_desk
        FROM activity
        WHERE jur_assignedgroup_id IS NOT NULL
    )
    SELECT 
        prev_desk as desk_id,
        COUNT(*) as bounces_initiated
    FROM DeskChanges
    WHERE current_desk != prev_desk AND prev_desk IS NOT NULL
    GROUP BY prev_desk
    ORDER BY bounces_initiated DESC;
    """
    df_desk_bounces = pd.read_sql_query(query_desk_stats, conn)
    
    conn.close()
    
    # --- Analysis & Reporting ---
    
    # KPI 1: The Pinball Score (Transfers Distribution)
    avg_transfers = df_transfers['transfer_count'].mean()
    median_transfers = df_transfers['transfer_count'].median()
    max_transfers = df_transfers['transfer_count'].max()
    p90_transfers = df_transfers['transfer_count'].quantile(0.90)
    
    # KPI 2: "Extreme Pinballs" (Tickets with > 5 transfers)
    extreme_pinballs = df_transfers[df_transfers['transfer_count'] >= 5]
    extreme_pinball_count = len(extreme_pinballs)
    extreme_pinball_percentage = (extreme_pinball_count / len(df_transfers)) * 100
    
    # KPI 3: "Hot Potato Champions" (Top Desks sending tickets away)
    # We need desk names if possible, but IDs are fine for now.
    top_bouncers = df_desk_bounces.head(5)
    
    # KPI 4: "Looping" (Distinct Desks vs Total Transfers)
    # If Transfer Count > (Distinct Desks - 1), it implies a return/loop.
    # Example: A->B (1 transfer, 2 desks). 1 > (2-1)? No. 1 = 1.
    # Example: A->B->A (2 transfers, 2 desks). 2 > (2-1)? Yes.
    
    df_transfers['is_loop'] = df_transfers['transfer_count'] > (df_transfers['distinct_desks'] - 1)
    loop_count = df_transfers['is_loop'].sum()
    loop_percentage = (loop_count / len(df_transfers)) * 100
    
    # Generate Markdown Report
    report = f"""
# 🎱 Pinball Effect: Executive KPI Report

**Goal:** Quantify the "Ping-Pong" behavior of tickets between departments.

## 1. The Chaos Factor (Global Transfer Metrics)
*   **Average Hops per Ticket:** {avg_transfers:.2f}
*   **Median Hops:** {median_transfers:.0f}
*   **The "90th Percentile" Nightmare:** 10% of tickets hop at least **{p90_transfers:.0f} times**.
*   **Maximum Observed Hops:** {max_transfers} (The "Champion")

## 2. "Hot Potatoes" (Extreme Pinball)
*   **Tickets with 5+ Transfers:** {extreme_pinball_count} tickets ({extreme_pinball_percentage:.2f}%)
    *   *Insight:* These {extreme_pinball_count} cases represent the "frozen middle" – tickets that consume disproportionate management time.

## 3. The "Loop" Index (Inefficiency)
*   **Loop Rate:** **{loop_percentage:.2f}%** of transferred tickets return to a desk they already visited.
    *   *Meaning:* A loop (A $\\rightarrow$ B $\\rightarrow$ A) is a pure waste of time. {loop_percentage:.2f}% of multi-desk tickets suffer from this.

## 4. Top "Ricochet" Desks (Biggest Senders)
*Who is pushing work away the most?*

| Rank | Desk ID | Bounces Initiated |
| :--- | :--- | :--- |
"""
    for i, row in top_bouncers.iterrows():
        report += f"| {i+1} | Desk {int(row['desk_id'])} | {row['bounces_initiated']} |\n"

    report += "\n\n*Generated by Pinball Analysis Module*"
    
    print(report)
    
    with open("analysis/pinball/pinball_kpi_report.md", "w") as f:
        f.write(report)

if __name__ == "__main__":
    calculate_kpis()
